### ISSUE TITLE
Remarkable Model

### ISSUE THREAD

**Issue by BartleyTheShopkeeper** [Evidlo/remarkable_syncthing#3]
Hello. 

I'm currently looking at getting a remarkable, but I'm torn between the first and second generation. I don't want to use a subscription model to sync documents. The remarkable 1 seems to have better support for tinkering and third party software like this. However the first generation has been discontinued, so I'm curious how good th support isfor second generation.

Does this support both? I use syncthing between my debian laptop and android phone and I adore it.

Thanks.

**Comment by jonZlotnik** [comment]
Seems to work great with my remarkable2 but [extra work](https://github.com/Evidlo/remarkable_syncthing/issues/1) is needed to get files to show up in the remarkable gui.
