### ISSUE TITLE
syncthingctl

### ISSUE THREAD

**Issue by mooomooo** [Evidlo/remarkable_syncthing#6]
Might it be possible to also port the CLI syncthingctl (from https://github.com/Martchus/syncthingtray)?  Either in this package or in a separate one.  With that, it'd be possible to configure / manage syncthing without needing another computer on the same network to access the web interface.

**Comment by Evidlo** [comment]
That's probably a question that belongs in [entware](https://github.com/Entware/Entware) issues.  I didn't create the syncthing package.
