### ISSUE TITLE
Viewing the files

### ISSUE THREAD

**Issue by wwvic** [Evidlo/remarkable_syncthing#7]
Hello! Thank you for the tutorial, it works and now there is a "Hello world!.pdf" file in the remarkable in a Sync folder. How can one access to the file from the remarkable? The list of files seems the same and looking for "Hello World" in the search button on the device it displays 0 results.

Also, how could I extract the pdf files from the device to the computer via the shared folder? 

Thank you in advance!

Vincenzo

**Comment by Evidlo** [comment]
That would indeed be nice, but due to the design of the reMarkable it's more complicated than that.  See the discussion [here](https://github.com/Evidlo/remarkable_syncthing/issues/1)
